<a href="https://colab.research.google.com/github/tanushkapatil/DEVL/blob/main/assignment_1c.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
result = arr1 + arr2
print(result)



[[ 8 10 12]
 [14 16 18]]


In [ ]:
import numpy as np

def matrix():
    r1 = int(input("Enter the number of rows for 1st matrix : "))
    c1 = int(input("Enter the number of columns for 1st matrix : "))
    arr1 = np.zeros((r1, c1), dtype=float)

    print("Enter the values for the 1st matrix:")
    for i in range(r1):
        for j in range(c1):
            arr1[i, j] = float(input(f"Enter value for element [{i}][{j}]: "))
    print("The first matrix is:")
    print(arr1)

    r2 = int(input("Enter the number of rows for 2nd matrix : "))
    c2 = int(input("Enter the number of columns for 2nd matrix: "))
    arr2 = np.zeros((r2, c2), dtype=float)

    print("Enter the values for the 2nd matrix:")
    for i in range(r2):
        for j in range(c2):
            arr2[i, j] = float(input(f"Enter value for element [{i}][{j}]: "))

    print("The second matrix is:")
    print(arr2)

    return arr1, arr2, r1, c1, r2, c2

def add(arr1, arr2):
    if arr1.shape == arr2.shape:
        addition_result = arr1 + arr2
        print("Matrix Addition Result:")
        print(addition_result)
    else:
        print("Matrix addition is not possible due to dimension mismatch.")

def sub(arr1, arr2):
    if arr1.shape == arr2.shape:
        subtraction_result = arr1 - arr2
        print("Matrix Subtraction Result:")
        print(subtraction_result)
    else:
        print("Matrix subtraction is not possible due to dimension mismatch.")

def mult(arr1, arr2, c1, r2):
    if c1 == r2:
        multiplication_result = np.dot(arr1, arr2)
        print("Matrix Multiplication Result:")
        print(multiplication_result)
    else:
        print("Matrix multiplication is not possible due to dimension mismatch.")


arr1, arr2, r1, c1, r2, c2 = matrix()

operations = {
        1: lambda: add(arr1, arr2),
        2: lambda: sub(arr1, arr2),
        3: lambda: mult(arr1, arr2, c1, r2)
    }

while True:
    print("\nSelect an operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Exit")

    choice = int(input("Enter your choice (1/2/3/4): "))

    if choice in operations:
        operations[choice]()
    elif choice == 4:
        print("Exited")
        break
    else:
        print("Invalid choice. Please choose again.")


Enter the number of rows for 1st matrix : 2
Enter the number of columns for 1st matrix : 2
Enter the values for the 1st matrix:
Enter value for element [0][0]: 1
Enter value for element [0][1]: 2
Enter value for element [1][0]: 3
Enter value for element [1][1]: 4
The first matrix is:
[[1. 2.]
 [3. 4.]]
Enter the number of rows for 2nd matrix : 2
Enter the number of columns for 2nd matrix: 2
Enter the values for the 2nd matrix:
Enter value for element [0][0]: 5
Enter value for element [0][1]: 6
Enter value for element [1][0]: 7
Enter value for element [1][1]: 8
The second matrix is:
[[5. 6.]
 [7. 8.]]

Select an operation:
1. Add
2. Subtract
3. Multiply
4. Exit
Enter your choice (1/2/3/4): 1
Matrix Addition Result:
[[ 6.  8.]
 [10. 12.]]

Select an operation:
1. Add
2. Subtract
3. Multiply
4. Exit
Enter your choice (1/2/3/4): 2
Matrix Subtraction Result:
[[-4. -4.]
 [-4. -4.]]

Select an operation:
1. Add
2. Subtract
3. Multiply
4. Exit
Enter your choice (1/2/3/4): 3
Matrix Multiplicati

In [ ]:
import numpy as np

def matrix():
    r1 = int(input("Enter the number of rows for 1st matrix : "))
    c1 = int(input("Enter the number of columns for 1st matrix : "))
    arr1 = np.zeros((r1, c1), dtype=float)

    print("Enter the values for the 1st matrix:")
    for i in range(r1):
        for j in range(c1):
            arr1[i, j] = float(input(f"Enter value for element [{i}][{j}]: "))
    print("The first matrix is:")
    print(arr1)

    r2 = int(input("Enter the number of rows for 2nd matrix : "))
    c2 = int(input("Enter the number of columns for 2nd matrix: "))
    arr2 = np.zeros((r2, c2), dtype=float)

    print("Enter the values for the 2nd matrix:")
    for i in range(r2):
        for j in range(c2):
            arr2[i, j] = float(input(f"Enter value for element [{i}][{j}]: "))

    print("The second matrix is:")
    print(arr2)


def add():
    if arr1.shape == arr2.shape:
        addition_result = arr1 + arr2
        print("Matrix Addition Result:")
        print(addition_result)
    else:
        print("Matrix addition is not possible due to dimension mismatch.")

def sub():
    if arr1.shape == arr2.shape:
        subtraction_result = arr1 - arr2
        print("Matrix Subtraction Result:")
        print(subtraction_result)
    else:
        print("Matrix subtraction is not possible due to dimension mismatch.")

def mult():
    if c1 == r2:
        multiplication_result = np.dot(arr1, arr2)
        print("Matrix Multiplication Result:")
        print(multiplication_result)
    else:
        print("Matrix multiplication is not possible due to dimension mismatch.")


matrix()

while True:
    print("\nSelect an operation:")
    print("1. Add")
    print("2. Subtract")
    print("3. Multiply")
    print("4. Exit")

    choice = int(input("Enter your choice (1/2/3/4): "))

    if choice == 1:
        add()
    elif choice == 2:
        sub()
    elif choice == 3:
        mult()
    elif choice == 4:
        print("Exited")
        break
    else:
        print("Invalid choice. Please choose again.")

Enter the number of rows for 1st matrix : 2
Enter the number of columns for 1st matrix : 2
Enter the values for the 1st matrix:
Enter value for element [0][0]: 1
Enter value for element [0][1]: 2
Enter value for element [1][0]: 3
Enter value for element [1][1]: 4
The first matrix is:
[[1. 2.]
 [3. 4.]]
Enter the number of rows for 2nd matrix : 2
Enter the number of columns for 2nd matrix: 2
Enter the values for the 2nd matrix:
Enter value for element [0][0]: 5
Enter value for element [0][1]: 6
Enter value for element [1][0]: 7
Enter value for element [1][1]: 8
The second matrix is:
[[5. 6.]
 [7. 8.]]

Select an operation:
1. Add
2. Subtract
3. Multiply
4. Exit
Enter your choice (1/2/3/4): 1
Matrix Addition Result:
[[ 6.  8.]
 [10. 12.]]

Select an operation:
1. Add
2. Subtract
3. Multiply
4. Exit
Enter your choice (1/2/3/4): 2
Matrix Subtraction Result:
[[-4. -4.]
 [-4. -4.]]

Select an operation:
1. Add
2. Subtract
3. Multiply
4. Exit
Enter your choice (1/2/3/4): 3
Matrix Multiplicati